### ISSUE TITLE
RelevantSearch is not working

### ISSUE THREAD

**Issue by vhanded** [jdgamble555/adv-firestore-functions#22]
Digging into your source code, I saw that the fields option is compulsory, with a type of string.

But, to execute the code, you need an array of string, not just string.

Might need a fix there, and also make field an optional property.

Thanks!

**Comment by jdgamble555** [comment]
You have to have field(s) to index.  It does not index the whole document, as this would be way overkill.  That is the reason it is required.  However, I made it so that you can input one field without it being in an array, although this was really overkill for the code:

https://github.com/jdgamble555/adv-firestore-functions/commit/342c562022943bedf0b81250a215302588f26e12

J

**Comment by stevebrowndotco** [comment]
Hello, 

If writing in typescript the fields property is still incorrectly a string type when it should be an array. Just a FYI :)

**Comment by jdgamble555** [comment]
I am not sure what you mean here, but I am no longer keeping up with this project, so you may want to fork it.
